services:
  test-db:
    container_name: test-db-pg
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data/test/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5436:5432"
    env_file:
      - app.env
    restart: unless-stopped
    networks:
      - test-backend
  test-pg-admin:
    container_name: test-pg-admin
    image: dpage/pgadmin4:7.2
    ports:
      - "5050:80"
    env_file:
      - app.env
    restart: unless-stopped
    networks:
      - test-backend
  test-app:
    container_name: test-app
    build: .
    links:
      - "test-db:database"
    env_file:
      - app.env
    ports:
      - 8001:8001
    restart: unless-stopped
    networks:
      - test-backend
values:
  - pg-data:
networks:
  test-backend:
    driver: bridge
    driver_opts:
       com.docker.network.bridge.host_bind_ipv4: "127.0.0.1"